package dao;

import entity.AugustdbDeliveryreceipt;
import java.util.List;

public interface AugustdbDeliveryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryreceipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryreceiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryreceipt
     *
     * @mbg.generated
     */
    int insert(AugustdbDeliveryreceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryreceipt
     *
     * @mbg.generated
     */
    AugustdbDeliveryreceipt selectByPrimaryKey(String deliveryreceiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryreceipt
     *
     * @mbg.generated
     */
    List<AugustdbDeliveryreceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryreceipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbDeliveryreceipt record);
}