package dao;

import entity.AugustdbManager;
import java.util.List;

public interface AugustdbManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_manager
     *
     * @mbg.generated
     */
    int insert(AugustdbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_manager
     *
     * @mbg.generated
     */
    AugustdbManager selectByPrimaryKey(String mgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_manager
     *
     * @mbg.generated
     */
    List<AugustdbManager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbManager record);
}