package dao;

import entity.AugustdbRoute;
import java.util.List;

public interface AugustdbRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String routeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_route
     *
     * @mbg.generated
     */
    int insert(AugustdbRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_route
     *
     * @mbg.generated
     */
    AugustdbRoute selectByPrimaryKey(String routeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_route
     *
     * @mbg.generated
     */
    List<AugustdbRoute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbRoute record);
}