package com.nf147.dao;

import entity.AugustdbCustomer;
import java.util.List;

public interface AugustdbCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_customer
     *
     * @mbg.generated
     */
    int insert(AugustdbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_customer
     *
     * @mbg.generated
     */
    AugustdbCustomer selectByPrimaryKey(String cuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_customer
     *
     * @mbg.generated
     */
    List<AugustdbCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbCustomer record);
}