package com.nf147.dao;

import entity.AugustdbCar;
import java.util.List;

public interface AugustdbCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_car
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_car
     *
     * @mbg.generated
     */
    int insert(AugustdbCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_car
     *
     * @mbg.generated
     */
    AugustdbCar selectByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_car
     *
     * @mbg.generated
     */
    List<AugustdbCar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_car
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbCar record);
}