package com.nf147.dao;

import entity.AugustdbDeliveryrange;
import java.util.List;

public interface AugustdbDeliveryrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryrange
     *
     * @mbg.generated
     */
    int insert(AugustdbDeliveryrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryrange
     *
     * @mbg.generated
     */
    AugustdbDeliveryrange selectByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryrange
     *
     * @mbg.generated
     */
    List<AugustdbDeliveryrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbDeliveryrange record);
}