package com.nf147.dao;

import entity.AugustdbCityarea;
import java.util.List;

public interface AugustdbCityareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_cityarea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_cityarea
     *
     * @mbg.generated
     */
    int insert(AugustdbCityarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_cityarea
     *
     * @mbg.generated
     */
    AugustdbCityarea selectByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_cityarea
     *
     * @mbg.generated
     */
    List<AugustdbCityarea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_cityarea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbCityarea record);
}