package com.nf147.dao;

import entity.AugustdbCity;
import java.util.List;

public interface AugustdbCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_city
     *
     * @mbg.generated
     */
    int insert(AugustdbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_city
     *
     * @mbg.generated
     */
    AugustdbCity selectByPrimaryKey(String cityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_city
     *
     * @mbg.generated
     */
    List<AugustdbCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbCity record);
}