package com.nf147.dao;

import entity.AugustdbDeliveryplace;
import java.util.List;

public interface AugustdbDeliveryplaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryplace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryplace
     *
     * @mbg.generated
     */
    int insert(AugustdbDeliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryplace
     *
     * @mbg.generated
     */
    AugustdbDeliveryplace selectByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryplace
     *
     * @mbg.generated
     */
    List<AugustdbDeliveryplace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_deliveryplace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbDeliveryplace record);
}