package dao;

import entity.AugustdbOrder;
import java.util.List;

public interface AugustdbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_order
     *
     * @mbg.generated
     */
    int insert(AugustdbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_order
     *
     * @mbg.generated
     */
    AugustdbOrder selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_order
     *
     * @mbg.generated
     */
    List<AugustdbOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table augustdb_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AugustdbOrder record);
}